FROM node:20-alpine AS build
WORKDIR /app
ARG VITE_PUBLIC_API_URL=http://localhost:5000/api/v1
ENV VITE_PUBLIC_API_URL=$VITE_PUBLIC_API_URL
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist
EXPOSE 5174
CMD ["serve", "-s", "dist", "-l", "5174"]
